### ISSUE TITLE
Encountering Issue

### ISSUE THREAD

**Issue by Dehunibun** [sks316/bcml-steamdeck#12] opened 2024-08-28 05:42 UTC
[bcml_installer.log](https://github.com/user-attachments/files/16776828/bcml_installer.log)

**Comment by sks316** [comment] 2024-08-28 12:03
Can you delete `/home/deck/miniconda3` and install [Miniconda with Python 3.8](https://repo.anaconda.com/miniconda/Miniconda3-py38_23.1.0-1-Linux-x86_64.sh)? It seems like Python 3.7 no longer works for some reason.

**Comment by sks316** [comment] 2024-09-02 06:19
Does installing [Miniconda with Python 3.8](https://repo.anaconda.com/miniconda/Miniconda3-py38_23.1.0-1-Linux-x86_64.sh) resolve the issue? Please let me know. If I don't get a response, I may close this issue as resolved.

**Comment by sks316** [comment] 2024-09-05 01:40
No response, closing as a duplicate of #7.

**Closed as not planned by sks316** 2024-09-05 01:40 UTC
